# Generated by Django 2.2.15 on 2020-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200825_0716"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="df",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
