# Generated by Django 2.2.15 on 2020-09-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_delete_demo"),
        ("users", "0006_auto_20200825_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_rating",
                to="home.NewAPP",
            ),
        ),
    ]
