# Generated by Django 2.2.15 on 2020-09-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
