# Generated by Django 2.2.15 on 2020-09-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
