# Generated by Django 2.2.15 on 2020-08-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="test",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
