# Generated by Django 2.2.15 on 2020-09-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_newapp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Demo",
        ),
    ]
