# Generated by Django 2.2.15 on 2020-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_newapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoApp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user2", models.BigIntegerField()),
            ],
        ),
    ]
