# Generated by Django 2.2.15 on 2020-09-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_test'),
        ('home', '0009_auto_20200903_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='option1',
        ),
        migrations.DeleteModel(
            name='DemoApp',
        ),
    ]
